version: '3.8'

services:
  db:
    image: postgres:12.16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rental_car
      - TZ=Asia/Ho_Chi_Minh
      - PGTZ=Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
