path: fe-config.yaml
admin_return_url: https://minhhungcar-admin.vercel.app/contracts/payments/
admin_base_url:  https://minhhungcar-admin.vercel.app/
tech_base_url: https://minhhungcar-technician.vercel.app/
